### ISSUE TITLE
Prestashop Cannot Edit Personal Info on My Account 

### ISSUE THREAD

**Issue by mani313** [LoginRadius/Social-Login-for-Prestashop#2]
Hi,

this is seems big issue on your awesome module. cannot edit personal info if i used facebook login to get into the website. (i tried in facebook only).

whenever edit the fields and click save it ask to fill password too. even i entered correct password (which is one i using for login) it shows password incorrect please fill again error.

how could we fix this ? any stable version resolved this issue ? or is it only for my site ?

hope it fixed asap. and its urgent too.

thanks in advance
Mani

**Comment by loginradius-dev** [comment]
Hi Mani, 

If you are logging in through a social account we do not have access to the password for this account in order to store it in the database. A random password is generated for the account. There are 2 options for retrieving this to allow users to update their profile:
1. In the loginradius module configuration->Social Login tab->Do you want to send emails to customer after new User registrations at your website? change this option to yes and an email wil be sent to the users email address with there password. 
2. Have the user reset the password for their account by using the prestashop forgot password functionality and the email address associated with the Facebook (or other social provider) accounts. 

Let me know if you have further questions on this. 
Thanks,

**Comment by mani313** [comment]
Hi,

thank you for quick reply. i appreciate your help.

yes I've enabled the "email to customer after new registration in module"
and created a new account, also i received email with password as you said.

when i use that password for login its is working. but still cannot  edit
personal infos in prestashop with that password. its says incorrect
password (see i used same one i received in email).

can you guess why is still wrong ? i looking sort out this issue asap.

thank you,
Mani

**Comment by GovindMalviya** [comment]
Hi Mani,

If login is working with that password and edit personal account is not that means this issue is not of our plugin.

Can you please check this issue by creating account by email id and after that edit your personal account.

If this issue comes only when you login via social network then please give us your website url so that we can debug your issue.

**Comment by mani313** [comment]
Hi,

really sorry for delayed reply. yes you're correct issue is with my site. I
cannot edit personal infos from any of login (social & normal login). then
i found a developer on freelancing site and fixed this issue now.

thank you for your helpful reply. and your suggestion absolutely worked
actually.

looking forward to use Login Radius plugin continuously. :)

regards,
Mani

**Comment by GovindMalviya** [comment]
Good to hear that your issue is resolved, I am closing this issue now. cheers!
